### ISSUE TITLE
Persisto block placement issues

### ISSUE THREAD

**Issue by BTKingly** [Warzone/Maps#224] opened 2019-04-10 17:09 UTC
On Persisto, it won't allow you to place blocks in the designated lanes. Although you can build anywhere else. No idea what the issue is, but I thought I'd create this to acknowledge it, and hopefully for someone more skilled than me to fix it.

**Comment by Owehttamy** [comment] 2019-10-16 16:02
I believe this was fixed. Request to close?

**Comment by Owehttamy** [comment] 2019-11-01 22:39
Request to close
![CloseIt](https://user-images.githubusercontent.com/47429979/68060474-7d782880-fcce-11e9-9e8c-87eda966f9ea.PNG)

**Comment by BennyDoesTheStuff** [comment] 2019-11-03 05:45
For now, I'm going to close this until this is clarified more. Not exactly too sure what the issue is here.

**Closed by BennyDoesTheStuff** 2019-11-03 05:45 UTC
